name: amuse-py313
channels:
  - conda-forge
dependencies:
# Separate installation of AMUSE v2025.9.0 required.
# See docs for details.
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alsa-lib=1.2.14
  - asttokens=3.0.0
  - attr=2.5.2
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bison=3.8.2
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.10.0
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - cfitsio=4.6.2
  - cftime=1.6.4
  - cmake=4.1.2
  - comm=0.2.3
  - conda-gcc-specs=13.4.0
  - contourpy=1.3.3
  - coreutils=9.5
  - cpython=3.13.7
  - curl=8.14.1
  - cxx-compiler=1.10.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - docutils=0.22.2
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fftw=3.3.10
  - flex=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fortran-compiler=1.10.0
  - freetype=2.14.1
  - gcc=13.4.0
  - gcc_impl_linux-64=13.4.0
  - gcc_linux-64=13.4.0
  - gfortran=13.4.0
  - gfortran_impl_linux-64=13.4.0
  - gfortran_linux-64=13.4.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.8
  - gxx=13.4.0
  - gxx_impl_linux-64=13.4.0
  - gxx_linux-64=13.4.0
  - gzip=1.14
  - h5py=3.14.0
  - harfbuzz=12.1.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - healpix_cxx=3.81
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.76
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.2
  - libclang13=21.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.4.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm21=21.1.2
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpmix=5.0.8
  - libpng=1.6.50
  - libpq=18.0
  - libsanitizer=13.4.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.4.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.9
  - libtiff=4.7.1
  - libudev1=257.9
  - libuuid=2.41.2
  - libuv=1.51.0
  - libvulkan-loader=1.4.313.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - m4=1.4.20
  - make=4.4.1
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpi4py=4.1.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openmpi=5.0.8
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - patch=2.8
  - pcre2=10.46
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python-gil=3.13.7
  - python_abi=3.13
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - rdma-core=59.0
  - readline=8.2
  - rhash=1.4.6
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - stack_data=0.6.3
  - sysroot_linux-64=2.34
  - tar=1.35
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucc=1.5.1
  - ucx=1.19.0
  - unzip=6.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
