name: amuse-py313
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - wheel
  - netcdf4
  - zlib
  - cxx-compiler
  - fftw
  - numpy
  - mpi4py[version='>=1.1.0']
  - openmpi
  - unzip
  - h5py[version='>=1.1.0']
  - curl
  - gzip
  - pkgconfig
  - xz
  - patch
  - make
  - hdf5
  - qhull
  - gsl
  - liblapack
  - mpfr
  - fortran-compiler
  - docutils[version='>=0.6']
  - c-compiler
  - coreutils
  - gfortran[version='<14']
  - perl
  - cmake
  - healpix_cxx
  - gmp
  - tar
  - libopenblas
  - bzip2
  - bison
  - ipykernel
  - matplotlib
  - cffi
  - setuptools
  - scipy
  - tqdm
  - corner
  - flake8
  - black
  - isort
  - scienceplots
